# Form implementation generated from reading ui file 'ihm/gui/qt_designer_files/medisecure.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 19, 781, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.creat_patient_folder = QtWidgets.QWidget()
        self.creat_patient_folder.setObjectName("creat_patient_folder")
        self.date_of_birth_input = QtWidgets.QDateEdit(parent=self.creat_patient_folder)
        self.date_of_birth_input.setGeometry(QtCore.QRect(400, 210, 151, 24))
        self.date_of_birth_input.setObjectName("date_of_birth_input")
        self.dob_label_2 = QtWidgets.QLabel(parent=self.creat_patient_folder)
        self.dob_label_2.setGeometry(QtCore.QRect(230, 260, 101, 21))
        self.dob_label_2.setObjectName("dob_label_2")
        self.firstname_input = QtWidgets.QLineEdit(parent=self.creat_patient_folder)
        self.firstname_input.setGeometry(QtCore.QRect(400, 80, 151, 21))
        self.firstname_input.setObjectName("firstname_input")
        self.lastname_input = QtWidgets.QLineEdit(parent=self.creat_patient_folder)
        self.lastname_input.setGeometry(QtCore.QRect(400, 120, 151, 21))
        self.lastname_input.setObjectName("lastname_input")
        self.dob_label = QtWidgets.QLabel(parent=self.creat_patient_folder)
        self.dob_label.setGeometry(QtCore.QRect(230, 210, 101, 21))
        self.dob_label.setObjectName("dob_label")
        self.email_input = QtWidgets.QLineEdit(parent=self.creat_patient_folder)
        self.email_input.setGeometry(QtCore.QRect(400, 160, 151, 21))
        self.email_input.setObjectName("email_input")
        self.cancel_create_folder_btn = QtWidgets.QPushButton(parent=self.creat_patient_folder)
        self.cancel_create_folder_btn.setGeometry(QtCore.QRect(520, 390, 113, 41))
        self.cancel_create_folder_btn.setObjectName("cancel_create_folder_btn")
        self.consent_checkbox = QtWidgets.QCheckBox(parent=self.creat_patient_folder)
        self.consent_checkbox.setGeometry(QtCore.QRect(400, 260, 87, 20))
        self.consent_checkbox.setObjectName("consent_checkbox")
        self.firstname_label = QtWidgets.QLabel(parent=self.creat_patient_folder)
        self.firstname_label.setGeometry(QtCore.QRect(230, 80, 101, 21))
        self.firstname_label.setObjectName("firstname_label")
        self.guardian_consent_checkbox = QtWidgets.QCheckBox(parent=self.creat_patient_folder)
        self.guardian_consent_checkbox.setGeometry(QtCore.QRect(400, 300, 87, 20))
        self.guardian_consent_checkbox.setObjectName("guardian_consent_checkbox")
        self.lastname_label = QtWidgets.QLabel(parent=self.creat_patient_folder)
        self.lastname_label.setGeometry(QtCore.QRect(230, 120, 101, 21))
        self.lastname_label.setObjectName("lastname_label")
        self.email_label = QtWidgets.QLabel(parent=self.creat_patient_folder)
        self.email_label.setGeometry(QtCore.QRect(230, 160, 101, 21))
        self.email_label.setObjectName("email_label")
        self.dob_label_3 = QtWidgets.QLabel(parent=self.creat_patient_folder)
        self.dob_label_3.setGeometry(QtCore.QRect(230, 300, 121, 21))
        self.dob_label_3.setObjectName("dob_label_3")
        self.create_folder_btn = QtWidgets.QPushButton(parent=self.creat_patient_folder)
        self.create_folder_btn.setGeometry(QtCore.QRect(380, 390, 113, 41))
        self.create_folder_btn.setObjectName("create_folder_btn")
        self.tabWidget.addTab(self.creat_patient_folder, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Medisecure"))
        self.dob_label_2.setText(_translate("MainWindow", "Patient"))
        self.dob_label.setText(_translate("MainWindow", "Date of birth"))
        self.cancel_create_folder_btn.setText(_translate("MainWindow", "Cancel"))
        self.consent_checkbox.setText(_translate("MainWindow", "Consented"))
        self.firstname_label.setText(_translate("MainWindow", "Firstname"))
        self.guardian_consent_checkbox.setText(_translate("MainWindow", "Consented"))
        self.lastname_label.setText(_translate("MainWindow", "Lastname"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.dob_label_3.setText(_translate("MainWindow", "Guardian (if minor)"))
        self.create_folder_btn.setText(_translate("MainWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.creat_patient_folder), _translate("MainWindow", "Patient Management"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
