# Form implementation generated from reading ui file 'ihm/gui/qt_designer_files/create_folder_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.firstname_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.firstname_input.setGeometry(QtCore.QRect(290, 70, 151, 21))
        self.firstname_input.setObjectName("firstname_input")
        self.lastname_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lastname_input.setGeometry(QtCore.QRect(290, 110, 151, 21))
        self.lastname_input.setObjectName("lastname_input")
        self.email_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_input.setGeometry(QtCore.QRect(290, 150, 151, 21))
        self.email_input.setObjectName("email_input")
        self.date_of_birth_input = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_of_birth_input.setGeometry(QtCore.QRect(290, 200, 151, 24))
        self.date_of_birth_input.setObjectName("date_of_birth_input")
        self.consent_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.consent_checkbox.setGeometry(QtCore.QRect(290, 250, 87, 20))
        self.consent_checkbox.setObjectName("consent_checkbox")
        self.guardian_consent_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.guardian_consent_checkbox.setGeometry(QtCore.QRect(290, 290, 87, 20))
        self.guardian_consent_checkbox.setObjectName("guardian_consent_checkbox")
        self.create_folder_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_folder_btn.setGeometry(QtCore.QRect(270, 380, 113, 41))
        self.create_folder_btn.setObjectName("create_folder_btn")
        self.cancel_create_folder_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_create_folder_btn.setGeometry(QtCore.QRect(410, 380, 113, 41))
        self.cancel_create_folder_btn.setObjectName("cancel_create_folder_btn")
        self.firstname_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.firstname_label.setGeometry(QtCore.QRect(120, 70, 101, 21))
        self.firstname_label.setObjectName("firstname_label")
        self.lastname_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.lastname_label.setGeometry(QtCore.QRect(120, 110, 101, 21))
        self.lastname_label.setObjectName("lastname_label")
        self.email_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(120, 150, 101, 21))
        self.email_label.setObjectName("email_label")
        self.dob_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.dob_label.setGeometry(QtCore.QRect(120, 200, 101, 21))
        self.dob_label.setObjectName("dob_label")
        self.dob_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.dob_label_2.setGeometry(QtCore.QRect(120, 250, 101, 21))
        self.dob_label_2.setObjectName("dob_label_2")
        self.dob_label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.dob_label_3.setGeometry(QtCore.QRect(120, 290, 121, 21))
        self.dob_label_3.setObjectName("dob_label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow: QtWidgets.QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create folder patient"))
        self.consent_checkbox.setText(_translate("MainWindow", "Consented"))
        self.guardian_consent_checkbox.setText(_translate("MainWindow", "Consented"))
        self.create_folder_btn.setText(_translate("MainWindow", "Create"))
        self.cancel_create_folder_btn.setText(_translate("MainWindow", "Cancel"))
        self.firstname_label.setText(_translate("MainWindow", "Firstname"))
        self.lastname_label.setText(_translate("MainWindow", "Lastname"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.dob_label.setText(_translate("MainWindow", "Date of birth"))
        self.dob_label_2.setText(_translate("MainWindow", "Patient"))
        self.dob_label_3.setText(_translate("MainWindow", "Guardian (if minor)"))
