name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      env:
        DISPLAY: ":99.0"
        DB_URL: mysql+pymysql://admin:admin@127.0.0.1:3306/medisecure
      run: |
        source venv/bin/activate
        xvfb-run python -m pytest -v --cov --cov-report=xml
