name: Setup Environment

on:
  workflow_call:

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
          libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 \
          libxcb-xinput0 libxcb-xfixes0 libxcb-shape0 libglib2.0-0 libgl1-mesa-dev
        sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev \
          libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
