name: Setup Environment

on:
  workflow_call:

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libegl1 libglib2.0-0 libx11-xcb1 libxcb-icccm4 \
        libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 \
        libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libgl1-mesa-glx \
        libgl1-mesa-dri

    - name: Start Xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -ac -screen 0 1920x1080x24 -nolisten tcp > /tmp/Xvfb.log 2>&1 &
