name: Upload Coverage

on:
  workflow_call:

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        working-directory: ./
        token: ${{ secrets.CODECOV_TOKEN }}
